### ISSUE TITLE
Android 5.1 & 6 (API Level 22 & 23) Runtime Issue : java.lang.NoClassDefFoundError in Kotlin Android Project.

### ISSUE THREAD

**Issue by rohan-tvm** [pubnub/kotlin#313]
What is the Issue:
- When running the app in Android API 22 and 23, I am getting `java.lang.NoClassDefFoundError` Exception when subscribing the channels:
> Process: com.example.mypubnubdemo, PID: 18586
                                         java.lang.NoClassDefFoundError: com.pubnub.internal.PubNubImpl$$ExternalSyntheticLambda0
                                         	at com.pubnub.internal.PubNubImpl.subscribe$pubnub_kotlin_impl(PubNubImpl.kt:1505)
                                         	at com.pubnub.internal.v2.subscription.SubscriptionImpl.subscribe(SubscriptionImpl.kt:94)
                                         	at com.pubnub.api.v2.subscriptions.SubscribeCapable$-CC.subscribe$default(SubscribeCapable.kt:16)
                                         	at com.example.mypubnubdemo.MainActivity.subscribeToChannels(MainActivity.kt:112)
                                         	at com.example.mypubnubdemo.MainActivity.initializePubNub(MainActivity.kt:63)
                                         	at com.example.mypubnubdemo.MainActivity$onCreate$1$1.invoke(MainActivity.kt:37)
                                         	at com.example.mypubnubdemo.MainActivity$onCreate$1$1.invoke(MainActivity.kt:36)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                         	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
                                         	at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:352)
                                         	at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:72)
                                         	at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:71)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                         	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                         	at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:64)
                                         	at com.example.mypubnubdemo.ui.theme.ThemeKt.MyPubNubDemoTheme(Theme.kt:53)
                                         	at com.example.mypubnubdemo.MainActivity$onCreate$1.invoke(MainActivity.kt:36)
                                         	at com.example.mypubnubdemo.MainActivity$onCreate$1.invoke(MainActivity.kt:35)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                         	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
                                         	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
                                         	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                         	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                         	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:186)
                                         	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:119)
                                         	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:118)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                         	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                         	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:110)
                                         	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:139)
                                         	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:138)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                         	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                         	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248)
                                         	at androidx.compose.ui.platform.WrappedComposi

What I did?
- Project configuration:

> minSdkVersion 22
> targetSdkVersion 35
> compileSdkVersion 35
> androidGradlePlugin "8.7.0"
> kotlinVersion "2.0.0"

- I declared the dependency `implementation ("com.pubnub:pubnub-kotlin:10.2.0")`  in app level's build.gradle file. 
- Initiate the PubNub client in MainActivity and subscribe the channel.
-  I tried to subscribe the channels in both ways, it is throwing the NoClassDefFoundError exception
- Subscription Way 1: 
> val channel = pubNub?.channel("my-channel-name")
> val options = SubscriptionOptions.receivePresenceEvents()
> val subscription = channel?.subscription(options)
> subscription?.addListener(eventCallback)
> subscription?.subscribe()

- Subscription Way 2:
> pubNub?.subscribe(listOf("my-channel-name"))

**Comment by wkal-pubnub** [comment]
Hello, you need to enable Java 8+ API and library desugaring in your Android build. Please take a look at these instructions:

https://developer.android.com/studio/write/java8-support#supported_features
https://developer.android.com/studio/write/java8-support#library-desugaring

I've verified that after enabling both and using Kotlin SDK 10.2.0 my test app doesn't crash when subscribing on an Android 5.1 emulator.

**Comment by rohan-tvm** [comment]
Thank you for the support 🙏 . 
It is working fine for me.
Would be good, if this is documented somewhere in the PubNub docs portal. 🙂
